using Microsoft.AspNetCore.Identity;

namespace InfoGen.Data
{
    public class ApplicationUser : IdentityUser
    {
        public string? StripeCustomerId { get; set; }

        /// <summary>Public display name for articles (e.g. "Article generated by X"). Defaults to email when null.</summary>
        public string? DisplayName { get; set; }
    }
}
